name: Iniciador de Workflow

on:
  discussion:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.

  call-reusable-workflow:
    strategy:
      matrix:
        nodeversion: [Uso1Remoto, Uso2Remoto, Uso3Remoto, Uso4Remoto]
    uses: zagato01/Lab_MarcoA_WorkflowReusable./.github/workflows/reusable-workflow-MarcoA.yml@main
    with:
      node: ${{ matrix.nodeversion }}
